### ISSUE TITLE
unavailable add-on

### ISSUE THREAD

**Issue by brandontle** [heroku/discussion#9]
Hi!

When inputting the `heroku addons:add heroku-postgresql:crane --version 9.2` line, I'm being told that the add-on plan is only available to select users.

Is there a way around this?

**Comment by raul** [comment]
Hey Brandon,
The instructions (and the code, I'm afraid) are pretty outdated. The `crane` database plan has become a legacy one - you can find its replacement in [this table](https://devcenter.heroku.com/articles/heroku-postgres-legacy-plans#first-generation-legacy-plans). You may want to start using one of the Starter databases to test if everything works as you expect and, in that case, switch to a Production one.
